### ISSUE TITLE
for youtube video 

### ISSUE THREAD

**Issue by zachysaur** [chow-q/wav2lip384#2]
Hey this is my youtube channel https://www.youtube.com/@socialapps1194
i want to make a video about your wav2lip if i get model that way you will hae peoples wanting to try this and buy your model

**Comment by chow-q** [comment]
Hi! Thank you for your interest in creating a video about our Wav2Lip model. Could you please send your contact information to my email at 313733727@qq.com? Looking forward to hearing from you!
